import { z } from 'zod'

/**
 * The lesson block vocabulary. One schema drives write validation (the
 * engine rejects a malformed block at save time), the TS types, and the
 * canonical field names — the editor and renderer can no longer disagree
 * about a key the way the old duck-typed blocks let them (the quiz answer
 * lived under `correct` in the editor and `correctAnswer` in the renderer,
 * so no quiz ever graded).
 */

/** Flow JSON is structurally validated by parseFlowState at render time. */
const flowData = z.record(z.string(), z.unknown())

/** Stable identity for editor reordering; generated by editor and migration. */
const blockBase = {
  id: z.string().default(''),
}

export const lessonBlockSchema = z.discriminatedUnion('type', [
  z.object({
    ...blockBase,
    type: z.literal('text'),
    content: z.string().default(''),
  }),
  z.object({
    ...blockBase,
    type: z.literal('heading'),
    // 1..3 map to h2..h4 on the page
    level: z.number().int().min(1).max(3).default(1),
    content: z.string().default(''),
  }),
  z.object({
    ...blockBase,
    type: z.literal('image'),
    url: z.string().default(''),
    alt: z.string().default(''),
    caption: z.string().default(''),
  }),
  z.object({
    ...blockBase,
    type: z.literal('video'),
    url: z.string().default(''),
    startTime: z.number().int().min(0).optional(),
    chapters: z
      .array(z.object({ time: z.number().min(0), title: z.string() }))
      .default([]),
  }),
  z.object({
    ...blockBase,
    type: z.literal('code'),
    language: z.string().default('cpp'),
    filename: z.string().default(''),
    code: z.string().default(''),
  }),
  z.object({
    ...blockBase,
    type: z.literal('callout'),
    variant: z.enum(['info', 'tip', 'warning', 'danger']).default('info'),
    content: z.string().default(''),
  }),
  z.object({
    ...blockBase,
    type: z.literal('download'),
    url: z.string().default(''),
    filename: z.string().default(''),
    description: z.string().default(''),
  }),
  z.object({
    ...blockBase,
    type: z.literal('quiz'),
    question: z.string().default(''),
    options: z.array(z.string()).default([]),
    correctAnswer: z.number().int().min(0).default(0),
    explanation: z.string().default(''),
  }),
  z.object({
    ...blockBase,
    type: z.literal('interactive_code'),
    language: z.string().default('cpp'),
    starterCode: z.string().default(''),
    solutionCode: z.string().default(''),
  }),
  z.object({
    ...blockBase,
    type: z.literal('diagram'),
    flowData: flowData.default({}),
  }),
  z.object({
    ...blockBase,
    type: z.literal('visual_blocks'),
    flowData: flowData.default({}),
    solutionFlowData: flowData.optional(),
  }),
  z.object({
    ...blockBase,
    type: z.literal('advanced_section'),
    title: z.string().default(''),
    content: z.string().default(''),
    defaultOpen: z.boolean().default(false),
  }),
  z.object({
    ...blockBase,
    type: z.literal('alternative_explanation'),
    title: z.string().default(''),
    content: z.string().default(''),
  }),
])

export type LessonBlock = z.infer<typeof lessonBlockSchema>
